---
name: gatk
command: gatk
parameters:
  -T 'UnifiedGenotyper'
  -R ''
  -I ''
  -nt '6'
  --dbsnp 'dbsnp.vcf'
  -stand_call_conf '30'
  -stand_emit_conf 10
  -o: 'commands'

# gatk -T UnifiedGenotyper -R reference.fasta -I inputfile.bam --dbsnp dbsnp.vcf (if any) -o output.vcf -nt numberofcores -stand_call_conf 30 -stand_emit_conf 10 -dcov 250
